### ISSUE TITLE
Linter does not support the generator’s new format

### ISSUE THREAD

**Issue by OlivierNicole** [tarides/okra#226] opened 2024-04-26 15:53 UTC
`okra generate` now makes the username in time entries a Markdown link, e.g., `[@OlivierNicole](https://github.com/OlivierNicole`. The issue is that this does not seem supported by the linker:
```
$ okra lint --okr-db=../../data/db.csv -e 16/OlivierNicole.md 17/OlivierNicole.md 
[ERROR(S)]: 16/OlivierNicole.md

In KR "General maintenance of OCaml including OCaml PR reviews":
  No time entry found. Each KR must be followed by '- @... (x days)'
[ERROR(S)]: 17/OlivierNicole.md

In KR "General maintenance of OCaml including OCaml PR reviews":
  No time entry found. Each KR must be followed by '- @... (x days)'
```

**Comment by shonfeder** [comment] 2024-04-28 23:09
With a freshly generated report from the main branch, that starts like this:

```
shonfeder week 17: 2024/04/22 -- 2024/04/28
```

I am also getting the following linting error:

```
    error  2: File format error at line 1, column 10: Parse error
```

This seems to point to the `w` in `week`.

**Comment by OlivierNicole** [comment] 2024-04-29 08:38
This makes me think that I forgot to specify the version I’m using: it seems to be the 0.4.0 release.

**Comment by shonfeder** [comment] 2024-04-29 08:56
Yeah, I think my issues be unrelated, as I hit different minting errors in ci: I think I should stick with the released version :)

**Comment by gpetiot** [comment] 2024-04-29 08:58
@OlivierNicole with okra 0.4.0 I tried to reproduce the bug on your weekly, but if I replace `(<X> days)` with a valid number the linting works fine.

@shonfeder this line doesn't cause any parsing error (either 0.4.0 or unreleased version).

**Comment by shonfeder** [comment] 2024-04-29 09:03
Yeah, I suspect it was giving a bad location? maybe it is due to something it doesn't like later in the report? If it recurs I'll, update. In the meantime I'll stick to the released version :)

**Comment by OlivierNicole** [comment] 2024-04-29 10:07
> @OlivierNicole with okra 0.4.0 I tried to reproduce the bug on your weekly, but if I replace `(<X> days)` with a valid number the linting works fine.

I’m confused: my weeklies 16 and 17 do not contain `(<X> days)`.

**Comment by jmid** [comment] 2024-04-29 10:53
> @OlivierNicole with okra 0.4.0 I tried to reproduce the bug on your weekly, but if I replace (<X> days) with a valid number the linting works fine.

I suspect this was using current `main` where those links were previously #193 #207 added IIRC.
- @OlivierNicole can you confirm that this was indeed with `main` ?
- @gpetiot can you reproduce with `main`?

**Comment by gpetiot** [comment] 2024-04-29 10:59
No I cannot reproduce the bug with main

**Comment by OlivierNicole** [comment] 2024-04-29 13:13
I just checked, and my version of okra does not generate clickable github handles.

Okay, I think what happened is that I generated those two reports with `main`, then a few days later came back and got confused: “why do I still have okra pinned?”, unpinned it and installed the 0.4.0 version, and ran the linter. Hence the inconsistency.

So this looks like a false alarm.

**Comment by gpetiot** [comment] 2024-04-29 13:20
Great, I will close this issue then, feel free to re-open if the issue arises again.

**Closed by gpetiot** 2024-04-29 13:20 UTC
